// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjsSNU8gti6g8hjg1Gk4Hq6OyjqzwWfI',
    appId: '1:680602701007:web:be7b16bcce2137fe9abbba',
    messagingSenderId: '680602701007',
    projectId: 'proyecto-30018',
    authDomain: 'proyecto-30018.firebaseapp.com',
    storageBucket: 'proyecto-30018.appspot.com',
    measurementId: 'G-P7EQWL1KDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfCclYZCNjQMzOsMbte7zpedSq003xkZE',
    appId: '1:680602701007:android:36b92ddf145f3d199abbba',
    messagingSenderId: '680602701007',
    projectId: 'proyecto-30018',
    storageBucket: 'proyecto-30018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4CYeanBa4zc3NPJ2ahBSNA6fmhn7gf48',
    appId: '1:680602701007:ios:94758ab2dd6b81489abbba',
    messagingSenderId: '680602701007',
    projectId: 'proyecto-30018',
    storageBucket: 'proyecto-30018.appspot.com',
    iosBundleId: 'com.example.practicoPostips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4CYeanBa4zc3NPJ2ahBSNA6fmhn7gf48',
    appId: '1:680602701007:ios:82d57419ec9fdf189abbba',
    messagingSenderId: '680602701007',
    projectId: 'proyecto-30018',
    storageBucket: 'proyecto-30018.appspot.com',
    iosBundleId: 'com.example.practicoPostips.RunnerTests',
  );
}
